# .github/workflows/cd-pipeline.yml
name: Python CD Pipeline

# 1. Trigger this workflow ONLY on pushes to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # 2. Grant permissions for the job to write to the GitHub Package Registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 3. Step to log in to the GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Step to build the Docker image and push it to the registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 5. Define the name of the image
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}